### ISSUE TITLE
Redmine 4 support?

### ISSUE THREAD

**Issue by mrPsycho** [syntacticvexation/redmine_favourite_projects#63] opened 2019-01-09 10:59 UTC
are there any plans to fix it for redmine 4?

now it show's error:
```
redmine@devcenter:~/redmine$ bundle exec rake redmine:plugins RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ApplicationHelper:Module
Did you mean?  alias_method
/home/redmine/redmine/plugins/redmine_favourite_projects/lib/favourite_projects_application_helper_patch.rb:8:in `block in included'
/home/redmine/redmine/plugins/redmine_favourite_projects/lib/favourite_projects_application_helper_patch.rb:7:in `class_eval'
/home/redmine/redmine/plugins/redmine_favourite_projects/lib/favourite_projects_application_helper_patch.rb:7:in `included'
/home/redmine/redmine/plugins/redmine_favourite_projects/init.rb:20:in `include'
/home/redmine/redmine/plugins/redmine_favourite_projects/init.rb:20:in `block in <top (required)>'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/redmine/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/home/redmine/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/redmine/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by syntacticvexation** [comment] 2019-01-13 03:48
Thanks for letting me know, I've been waiting for sameersbn/docker-redmine to release a 4.0.0 image. I'll expedite getting my devel environment sorted and take a look at this.

**Comment by syntacticvexation** [comment] 2019-01-18 09:04
Just an update, I've reproduced the error, it appears to be a common issue for any plugin that utilises alias_method_chain to wrap internal methods in Redmine 4. This is because Redmine 4 uses Rails 5 which no longer supports that method. I've filed an issue with Redmine around the preferred way to wrap methods without alias_method_chain (http://www.redmine.org/issues/30462), I'm assuming it will look like this https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/ but I'll hold off doing any sort of proper release until I get an answer on that query. In the meantime, I'll have a play and setup an unstable branch for attempts to address this for Redmine 4 users.

**Comment by syntacticvexation** [comment] 2019-01-21 13:46
Have a try of the 1.0-compatible branch and let me know how you get on.

**Comment by rtf67** [comment] 2019-01-23 22:21
I had the same issue with (master) branch, (1.0-unstable) seems to work

**Comment by syntacticvexation** [comment] 2019-03-11 09:55
Cool, so I've moved 1.0 to the master branch and tagged the old version. I'll close this ticket for the time being.

**Closed** 2019-03-11 09:55 UTC
